### ISSUE TITLE
The items file changed

### ISSUE THREAD

**Issue by Xaratas** [Xaratas/pillarsofeternity-2-Enhanced-UI#4]
All Afflictions and Inspirations are missing in the items file after you added the damage kinds.

**Comment by Spherikal** [comment]
I'm having trouble seeing the issue, could you give an example of a missing affliction or inspiration? Are they missing in game or in the .stringtable file?

I'll check it out tonight and see if I can find what's causing the problem!

**Comment by Xaratas** [comment]
@Spherikal Had to take the 0.5 beta offline. The statuseffect file was broken, looks like your regex eats a few female texts in some cases.

Try to get the pre-comit hook running. It will protect you from such mistakes. 
Hm, I see the readme file for that is only in german.

The file pre-commit in the translation_helper folder need to be copied into the hidden .git/hooks folder on the top level of the git. Thats all for windows. On linux its good to set the executeable bit. 
Then it checks all stringtable files which you try to commit. And shows a message and an epicfail and does nothing. So you can fix them and retry the commit.

**Comment by Xaratas** [comment]
Looks like the Items are back. Some of the abilities hide their keywords in clever english wording.

**Comment by Spherikal** [comment]
Yeah, it's annoying that they don't spell out all the inspirations and afflictions in the descriptions. It's probably something I'll have to do manually for each missing entry so it might take some time.

I tried to get the pre-commit file working but when I try to commit I get the following error:
```
Commit failed - exit code 1 received, with output: 'error: cannot spawn .git/hooks/pre-commit: No such file or directory'
```
I placed the pre-commit file in the .git/hooks/ folder like you instructed. Do I need to place the file in a folder called "pre-commit" as well?

**Comment by Xaratas** [comment]
The location is correct. 
Which git client software did you choose? The messaga makes me think that it has no „bash“ at hand and could not execute the pre-commit hook.

**Comment by Spherikal** [comment]
I'm using the GitHub Desktop client, how would I add a "bash" (I'm not sure what that is actually)?

Btw, I re-uploaded the 0.5-beta with the added corrections - hopefully it wont cause any big issues this time!

**Comment by Spherikal** [comment]
Got it to work!

Just had to change the `#!/bin/bash -` to `#!/bin/sh -`

**Comment by Spherikal** [comment]
Nope, I was wrong... Now I'm getting 
```
Commit failed - exit code 1 received, with output: '.git/hooks/pre-commit: ./tools/translation_helper/xsdv.sh: /bin/bash^M: bad interpreter: No such file or directory

 ----------------------------------------------- 
|       * * * E P I C F A I L * * *             |
|     Some files do not pass XML validation     |
|        Git commit has been aborted.           |
 -----------------------------------------------'
```
Instead :(

**Comment by Xaratas** [comment]
Ok, if you only have /bin/sh and not /bin/bash you have to change it also in this file:
/tools/translation_helper/xsdv.sh

It's also on the first line.

**Comment by Spherikal** [comment]
Getting closer? 😅 
After changing xsdv.sh I get this error:
```
Commit failed - exit code 1 received, with output: './tools/translation_helper/xsdv.sh: line 11: java: command not found

 ----------------------------------------------- 
|       * * * E P I C F A I L * * *             |
|     Some files do not pass XML validation     |
|        Git commit has been aborted.           |
 -----------------------------------------------'
```

**Comment by Xaratas** [comment]
Oh, yes, I did not mention that you need the java runtime. I hoped you have it already installed.
Here is the link to install it without the bullshit installer on java.com http://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html

**Comment by Spherikal** [comment]
Aaaahh finally! It works now 😄
