### ISSUE TITLE
I want to translate it to Korean

### ISSUE THREAD

**Issue by Xinkle** [Xaratas/pillarsofeternity-2-Enhanced-UI#7]
I want to translate it into Korean

how can I do?

**Comment by Xaratas** [comment]
Hello Xinkle, 

As i don't know anything about the behavior of Korean words (or Korean in general for that matter), we have 2 general options.

The first and most stable one is to provide the words and their forms which should be colorized and marked with an image, to the tool. The tool is this java code https://github.com/Xaratas/pillarsofeternity-2-german-patch/blob/master/translation_helper/PoE2%20-%20eclipse%20project%20text%20normalisierer/src/base/StringtableFile.java#L805 which i use to add the markup automatically.
The tool works with regular expressions to find the words and apply the markup.

The tool orients at the English markup base, and tries to make the same changes to the other languages.
The Korean translation is only available from the Korean distributor, so we would need these files
* abilities.stringtable
* statuseffects.stringtable
* gui.stringtable
* item.stringtable
* cyclopedia.stringtable
in Korean.

The second option would be, that you apply all the markup by hand to the 5 files, and supply these.


Feel free to ask any questions.

**Comment by Xinkle** [comment]
[enhanced_ui_korean_xinkle.zip](https://github.com/Xaratas/pillarsofeternity-2-Enhanced-UI/files/2167677/enhanced_ui_korean_xinkle.zip)

![image](https://user-images.githubusercontent.com/16386743/42339539-3ab09c40-80c8-11e8-9d2e-3d7ea2399e2e.png)

![image](https://user-images.githubusercontent.com/16386743/42339680-a70ba34e-80c8-11e8-9741-b80f2ea2cc9f.png)


I translated it into Korean. can you release it to nexus?
I changed a lot of code, I will request to pull later if you need it.

**Comment by Xaratas** [comment]
Yes, I will do a release.
Is there a link to point people to full Korean language files?

**Comment by Xinkle** [comment]
u mean original korean language file?

**Comment by Xaratas** [comment]
I mean the full Korean translation. It is not included in the downloads from Steam, Gog, Origin or the Mac Appstore. So for anyone not using the version from the Korean distributor the five files alone would be not very helpful.

**Comment by Xaratas** [comment]
I put a new version including your files up and added you to the credits. Thanks.

**Comment by Xinkle** [comment]
Korean version is provided exclusively through distributor 'Direct Games' (of course, steam key is provided). Most Koreans purchase the game through Direct Games and use Korean version and this mode will be very helpful.

**Comment by Xinkle** [comment]
Thanks for helping XD
